spring:
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017
  cloud:
    function:
      definition: productAccount
    stream:
      rabbit:
        bindings:
          productAccount-in-0:
            consumer:
              bindQueue: false
      bindings:
        ## destination = rabbitMQ exchange 와 같다
        ## group = rabbitMQ queue 와 같다
        productAccount-in-0:
          binder: rabbit
          destination: product
          group: account
  rabbitmq:
    host: localhost
    port: 5672
    username: client
    password: client
