spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product
  cloud:
    function:
      definition: consumeCompany
    stream:
      bindings:
        consumeCompany-in-0:
          binder: rabbit
          destination: company
          group: company-queue
          durableSubscription: true
  rabbitmq:
    host: localhost # rabbitMQ host
    port: 5672 # default port
    username: guest # default username
    password: guest # default password
