spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product
  cloud:
    #function: receivePayload
    stream:
      bindings:
        output:
          group: company-queue
          destination: company
        input:
          group: company-queue
          destination: company

