spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product
  cloud:
    function:
      definition: consumeCompany
    stream:
      bindings:
        consumeCompany-in-0:
          binder: rabbit
          destination: company
          group: company-queue
          durableSubscription: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
