spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product
  cloud:
    stream:
      bindings:
        company-in:
          destination: companyIn
          contentType: application/json
      rabbit:
        bindings:
          company-in:
            producer:
              exchangeType: fanout


